# Generated by Django 4.1.7 on 2023-03-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
